//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.17 at 10:24:25 PM EET 
//

package com.media2359.routeparser.tcx.model;

import org.simpleframework.xml.Element;
import org.simpleframework.xml.Namespace;
import org.simpleframework.xml.Root;

@Root(name = "Step_t", strict = false)
@Namespace(reference = "http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2")
public class StepT
        extends AbstractStepT {

    @Element(name = "Name", required = false)
    protected String name;
    @Element(name = "Duration", required = true)
    protected DurationT duration;
    @Element(name = "Intensity", required = true)
    protected IntensityT intensity;
    @Element(name = "Target", required = true)
    protected TargetT target;

    /**
     * Gets the value of the name property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the duration property.
     *
     * @return
     *     possible object is
     *     {@link DurationT }
     *
     */
    public DurationT getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     *
     * @param value
     *     allowed object is
     *     {@link DurationT }
     *
     */
    public void setDuration(DurationT value) {
        this.duration = value;
    }

    /**
     * Gets the value of the intensity property.
     *
     * @return
     *     possible object is
     *     {@link IntensityT }
     *
     */
    public IntensityT getIntensity() {
        return intensity;
    }

    /**
     * Sets the value of the intensity property.
     *
     * @param value
     *     allowed object is
     *     {@link IntensityT }
     *
     */
    public void setIntensity(IntensityT value) {
        this.intensity = value;
    }

    /**
     * Gets the value of the target property.
     *
     * @return
     *     possible object is
     *     {@link TargetT }
     *
     */
    public TargetT getTarget() {
        return target;
    }

    /**
     * Sets the value of the target property.
     *
     * @param value
     *     allowed object is
     *     {@link TargetT }
     *
     */
    public void setTarget(TargetT value) {
        this.target = value;
    }

}
