package akio.apps._base.utils

import android.util.SparseArray
import java.util.*

object PhoneNumberHelper {
	
	private const val MAX_COUNTRY_CODES = 215
	fun createCountryCodeToRegionCodeMap(): SparseArray<List<String>> {
		val map = SparseArray<List<String>>(MAX_COUNTRY_CODES)
		
		map.put(
			1, listOf("US", "AG", "AI", "AS", "BB", "BM", "BS", "CA", "DM", "DO", "GD", "GU", "JM", "KN", "KY", "LC", "MP", "MS", "PR", "SX", "TC", "TT", "VC", "VG", "VI")
		)
		map.put(7, listOf("RU", "KZ"))
		map.put(20, listOf("EG"))
		map.put(27, listOf("ZA"))
		map.put(30, listOf("GR"))
		map.put(31, listOf("NL"))
		map.put(32, listOf("BE"))
		map.put(33, listOf("FR"))
		map.put(34, listOf("ES"))
		map.put(36, listOf("HU"))
		map.put(39, listOf("IT"))
		map.put(40, listOf("RO"))
		map.put(41, listOf("CH"))
		map.put(43, listOf("AT"))
		map.put(44, listOf("GB", "GG", "IM", "JE"))
		map.put(45, listOf("DK"))
		map.put(46, listOf("SE"))
		map.put(47, listOf("NO", "SJ"))
		map.put(48, listOf("PL"))
		map.put(49, listOf("DE"))
		map.put(51, listOf("PE"))
		map.put(52, listOf("MX"))
		map.put(53, listOf("CU"))
		map.put(54, listOf("AR"))
		map.put(55, listOf("BR"))
		map.put(56, listOf("CL"))
		map.put(57, listOf("CO"))
		map.put(58, listOf("VE"))
		map.put(60, listOf("MY"))
		map.put(61, listOf("AU", "CC", "CX"))
		map.put(62, listOf("ID"))
		map.put(63, listOf("PH"))
		map.put(64, listOf("NZ"))
		map.put(65, listOf("SG"))
		map.put(66, listOf("TH"))
		map.put(81, listOf("JP"))
		map.put(82, listOf("KR"))
		map.put(84, listOf("VN"))
		map.put(86, listOf("CN"))
		map.put(90, listOf("TR"))
		map.put(91, listOf("IN"))
		map.put(92, listOf("PK"))
		map.put(93, listOf("AF"))
		map.put(94, listOf("LK"))
		map.put(95, listOf("MM"))
		map.put(98, listOf("IR"))
		map.put(211, listOf("SS"))
		map.put(212, listOf("MA", "EH"))
		map.put(213, listOf("DZ"))
		map.put(216, listOf("TN"))
		map.put(218, listOf("LY"))
		map.put(220, listOf("GM"))
		map.put(221, listOf("SN"))
		map.put(222, listOf("MR"))
		map.put(223, listOf("ML"))
		map.put(224, listOf("GN"))
		map.put(225, listOf("CI"))
		map.put(226, listOf("BF"))
		map.put(227, listOf("NE"))
		map.put(228, listOf("TG"))
		map.put(229, listOf("BJ"))
		map.put(230, listOf("MU"))
		map.put(231, listOf("LR"))
		map.put(232, listOf("SL"))
		map.put(233, listOf("GH"))
		map.put(234, listOf("NG"))
		map.put(235, listOf("TD"))
		map.put(236, listOf("CF"))
		map.put(237, listOf("CM"))
		map.put(238, listOf("CV"))
		map.put(239, listOf("ST"))
		map.put(240, listOf("GQ"))
		map.put(241, listOf("GA"))
		map.put(242, listOf("CG"))
		map.put(243, listOf("CD"))
		map.put(244, listOf("AO"))
		map.put(245, listOf("GW"))
		map.put(246, listOf("IO"))
		map.put(247, listOf("AC"))
		map.put(248, listOf("SC"))
		map.put(249, listOf("SD"))
		map.put(250, listOf("RW"))
		map.put(251, listOf("ET"))
		map.put(252, listOf("SO"))
		map.put(253, listOf("DJ"))
		map.put(254, listOf("KE"))
		map.put(255, listOf("TZ"))
		map.put(256, listOf("UG"))
		map.put(257, listOf("BI"))
		map.put(258, listOf("MZ"))
		map.put(260, listOf("ZM"))
		map.put(261, listOf("MG"))
		map.put(262, listOf("RE", "YT"))
		map.put(263, listOf("ZW"))
		map.put(264, listOf("NA"))
		map.put(265, listOf("MW"))
		map.put(266, listOf("LS"))
		map.put(267, listOf("BW"))
		map.put(268, listOf("SZ"))
		map.put(269, listOf("KM"))
		map.put(290, listOf("SH", "TA"))
		map.put(291, listOf("ER"))
		map.put(297, listOf("AW"))
		map.put(298, listOf("FO"))
		map.put(299, listOf("GL"))
		map.put(350, listOf("GI"))
		map.put(351, listOf("PT"))
		map.put(352, listOf("LU"))
		map.put(353, listOf("IE"))
		map.put(354, listOf("IS"))
		map.put(355, listOf("AL"))
		map.put(356, listOf("MT"))
		map.put(357, listOf("CY"))
		map.put(358, listOf("FI", "AX"))
		map.put(359, listOf("BG"))
		map.put(370, listOf("LT"))
		map.put(371, listOf("LV"))
		map.put(372, listOf("EE"))
		map.put(373, listOf("MD"))
		map.put(374, listOf("AM"))
		map.put(375, listOf("BY"))
		map.put(376, listOf("AD"))
		map.put(377, listOf("MC"))
		map.put(378, listOf("SM"))
		map.put(379, listOf("VA"))
		map.put(380, listOf("UA"))
		map.put(381, listOf("RS"))
		map.put(382, listOf("ME"))
		map.put(385, listOf("HR"))
		map.put(386, listOf("SI"))
		map.put(387, listOf("BA"))
		map.put(389, listOf("MK"))
		map.put(420, listOf("CZ"))
		map.put(421, listOf("SK"))
		map.put(423, listOf("LI"))
		map.put(500, listOf("FK"))
		map.put(501, listOf("BZ"))
		map.put(502, listOf("GT"))
		map.put(503, listOf("SV"))
		map.put(504, listOf("HN"))
		map.put(505, listOf("NI"))
		map.put(506, listOf("CR"))
		map.put(507, listOf("PA"))
		map.put(508, listOf("PM"))
		map.put(509, listOf("HT"))
		map.put(590, listOf("GP", "BL", "MF"))
		map.put(591, listOf("BO"))
		map.put(592, listOf("GY"))
		map.put(593, listOf("EC"))
		map.put(594, listOf("GF"))
		map.put(595, listOf("PY"))
		map.put(596, listOf("MQ"))
		map.put(597, listOf("SR"))
		map.put(598, listOf("UY"))
		map.put(599, listOf("CW", "BQ"))
		map.put(670, listOf("TL"))
		map.put(672, listOf("NF"))
		map.put(673, listOf("BN"))
		map.put(674, listOf("NR"))
		map.put(675, listOf("PG"))
		map.put(676, listOf("TO"))
		map.put(677, listOf("SB"))
		map.put(678, listOf("VU"))
		map.put(679, listOf("FJ"))
		map.put(680, listOf("PW"))
		map.put(681, listOf("WF"))
		map.put(682, listOf("CK"))
		map.put(683, listOf("NU"))
		map.put(685, listOf("WS"))
		map.put(686, listOf("KI"))
		map.put(687, listOf("NC"))
		map.put(688, listOf("TV"))
		map.put(689, listOf("PF"))
		map.put(690, listOf("TK"))
		map.put(691, listOf("FM"))
		map.put(692, listOf("MH"))
		map.put(800, listOf("001"))
		map.put(808, listOf("001"))
		map.put(850, listOf("KP"))
		map.put(852, listOf("HK"))
		map.put(853, listOf("MO"))
		map.put(855, listOf("KH"))
		map.put(856, listOf("LA"))
		map.put(870, listOf("001"))
		map.put(878, listOf("001"))
		map.put(880, listOf("BD"))
		map.put(881, listOf("001"))
		map.put(882, listOf("001"))
		map.put(883, listOf("001"))
		map.put(886, listOf("TW"))
		map.put(888, listOf("001"))
		map.put(960, listOf("MV"))
		map.put(961, listOf("LB"))
		map.put(962, listOf("JO"))
		map.put(963, listOf("SY"))
		map.put(964, listOf("IQ"))
		map.put(965, listOf("KW"))
		map.put(966, listOf("SA"))
		map.put(967, listOf("YE"))
		map.put(968, listOf("OM"))
		map.put(970, listOf("PS"))
		map.put(971, listOf("AE"))
		map.put(972, listOf("IL"))
		map.put(973, listOf("BH"))
		map.put(974, listOf("QA"))
		map.put(975, listOf("BT"))
		map.put(976, listOf("MN"))
		map.put(977, listOf("NP"))
		map.put(979, listOf("001"))
		map.put(992, listOf("TJ"))
		map.put(993, listOf("TM"))
		map.put(994, listOf("AZ"))
		map.put(995, listOf("GE"))
		map.put(996, listOf("KG"))
		map.put(998, listOf("UZ"))
		
		return map
	}

}