name: Develop PR Checks

on:
  pull_request:
    branches:
      - develop

jobs:
  lint:
    name: Develop PR - Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install ktlint
        uses: nbadal/action-ktlint-setup@v1
        with:
          ktlint_version: '0.48.2'

      - run: ktlint
        shell: bash

  build:
    name: Develop PR - Unit Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Make local.properties
        env:
          MAPBOX_DEV_TOKEN: sk.eyJ1IjoiYWtob2k5MCIsImEiOiJjbGUwMjNxa3AwNDEzM3Fyejh6b2ZrNGw3In0.mSo-Z30lqYW4K2Ime0z62g
        run: echo -e "mapbox.downloads.token=$MAPBOX_DEV_TOKEN" > local.properties

      - name: Build Debug APK
        run: bash ./gradlew :app:assembleDebug

      - name: Run unit tests
        run: bash ./gradlew testDebugUnitTest
