name: Release PR Checks

on:
  pull_request:
    branches: [ release/ ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: "Install ktlint"
        uses: nbadal/action-ktlint-setup@v1

      - run: ktlint
        shell: bash

  build:
    name: Build & Test
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout The Code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Configure Release Build Credentials
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.RELEASE_GOOGLE_SERVICES_JSON_BASE64 }}
          REGISTRATION_CREDENTIALS: ${{ secrets.RELEASE_REGISTRATION_CREDENTIALS_BASE64 }}
          LOCATION_CREDENTIALS: ${{ secrets.RELEASE_LOCATION_CREDENTIALS_BASE64 }}
          MAPBOX_DOWNLOAD_TOKEN: ${{ secrets.MAPBOX_SDK_DOWNLOAD_TOKEN }}
        run: |
          mkdir app/src/release/
          echo "$GOOGLE_SERVICES_JSON" > google-services.json.b64
          base64 -d -i google-services.json.b64 > app/src/release/google-services.json
          mkdir -p registration/src/release/res/values/
          echo "$REGISTRATION_CREDENTIALS" > reg_credentials.xml.b64
          base64 -d -i reg_credentials.xml.b64 > registration/src/release/res/values/credentials.xml
          mkdir -p data/location/src/release/res/values/
          echo "$LOCATION_CREDENTIALS" > loc_credentials.xml.b64
          base64 -d -i loc_credentials.xml.b64 > data/location/src/release/res/values/credentials.xml
          touch local.properties & echo -e "mapbox.downloads.token=$MAPBOX_DOWNLOAD_TOKEN" >> local.properties

      - name: Build Release APK
        run: bash ./gradlew :app:assembleRelease

      - name: Run Release Unit Tests
        run: bash ./gradlew testReleaseUnitTest
